version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fishTrack
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpadmin:
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
      PMA_PORT: 3306
      PMA_PASSWORD: root
      PMA_USER: root
